exports.handler = async function(event) {
  try {
    const body = JSON.parse(event.body || '{}');
    const userMessage = body.message || 'Hello';
    const lower = userMessage.toLowerCase();
    
    // Check if user wants an image
    const isImageRequest = lower.includes('generate image') || lower.includes('create image') || lower.includes('draw') || lower.includes('picture of') || lower.includes('make an image') || lower.startsWith('/image');
    
    if (isImageRequest) {
      // Extract prompt
      let imagePrompt = userMessage.replace(/generate image|create image|draw|picture of|make an image|\/image/gi, '').trim();
      if(!imagePrompt) imagePrompt = 'beautiful landscape';
      
      const imageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(imagePrompt)}?width=1024&height=1024&seed=${Math.floor(Math.random()*10000)}&nologo=true`;
      
      return {
        statusCode: 200,
        headers: { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" },
        body: JSON.stringify({ 
          reply: `Here is your image for: **${imagePrompt}**\n\n![${imagePrompt}](${imageUrl})\n\nGenerated by GAK AI ✨`,
          imageUrl: imageUrl
        })
      };
    }
    
    // Normal text chat
    const prompt = `You are GAK AI, created by Isaiah Gak Agok from South Sudan. Be helpful, friendly, concise. If user asks to generate image, tell them to say 'generate image of ...' . User asks: ${userMessage}`;
    
    const aiRes = await fetch('https://text.pollinations.ai/' + encodeURIComponent(prompt));
    const aiText = await aiRes.text();
    
    return {
      statusCode: 200,
      headers: { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" },
      body: JSON.stringify({ reply: aiText })
    };
  } catch (e) {
    return {
      statusCode: 200,
      headers: { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" },
      body: JSON.stringify({ reply: "I'm GAK AI! Small issue - please try again!" })
    };
  }
}
